---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nop
  labels: 
    app: nopcommerce
spec:
  minReadySeconds: 3
  replicas: 3
  selector:
    matchLabels: 
      app: nop
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      name: nop
      labels:
        app: nop
    spec:
      containers:
        - name: nop
          image: springcommunity/spring-framework-petclinic
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            failureThreshold: 2
            httpGet: 
              port: 8080
              path: /
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 2
            httpGet: 
              port: 8080
              path: /
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1