---
apiVersion: v1
kind: Service
metadata:
  name: nop
  labels:
    app: nop
spec:
  type: LoadBalancer
  selector:
    app: nop
  ports:
    - name: nop-svc
      port: 5000
      targetPort: 5000
      protocol: TCP 
  